POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk4MjcxMjIsInN1YiI6IjU2M2VhNGUwLTEyY2ItNGU1MS1hZjRiLTYzNDgwYTc1MTc0NCJ9.iywSNLbO4kOEhLnfrwSBug_YN3g3OD7ENZ9JRZI4yFQ

{
  "name": "Product 4",
  "price": 100.0
}

###

GET http://localhost:8080/products/21bcb6cc-854c-4795-a9ad-ea757f596993 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk4MjcxMjIsInN1YiI6IjU2M2VhNGUwLTEyY2ItNGU1MS1hZjRiLTYzNDgwYTc1MTc0NCJ9.iywSNLbO4kOEhLnfrwSBug_YN3g3OD7ENZ9JRZI4yFQ

###

GET http://localhost:8080/products HTTP/1.1
Content-Type: application/json
#para pegar o token de autenticação é só fazer uma requisição em user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk4Mjc5MzcsInN1YiI6IjU2M2VhNGUwLTEyY2ItNGU1MS1hZjRiLTYzNDgwYTc1MTc0NCJ9.2qLki0zG1SxwswBeviCeRtEND1NaC4iI8rlw4A713lI

###

PUT http://localhost:8080/products/21bcb6cc-854c-4795-a9ad-ea757f596993 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk4MjcxMjIsInN1YiI6IjU2M2VhNGUwLTEyY2ItNGU1MS1hZjRiLTYzNDgwYTc1MTc0NCJ9.iywSNLbO4kOEhLnfrwSBug_YN3g3OD7ENZ9JRZI4yFQ

{
"name": "Product Updated",
"price": 200.0
}

###

DELETE http://localhost:8080/products/21bcb6cc-854c-4795-a9ad-ea757f596993 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTk4MjcxMjIsInN1YiI6IjU2M2VhNGUwLTEyY2ItNGU1MS1hZjRiLTYzNDgwYTc1MTc0NCJ9.iywSNLbO4kOEhLnfrwSBug_YN3g3OD7ENZ9JRZI4yFQ